import { type NextPage } from "next";
import Head from "next/head";
import { MainLayout } from "../modules/layouts/MainLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div>Hello</div>
      </MainLayout>
    </>
  );
};

export default Home;
