import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { MainLayout } from "../modules/layouts/MainLayout";

const RestrictedPage: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{session ? "Fleff" : "Pleff"}</MainLayout>
    </>
  );
};

export default RestrictedPage;
